-- 코드를 입력하세요
SELECT U.USER_ID,U.NICKNAME, CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) as 전체주소,
CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8)) as 전화번호
FROM USED_GOODS_USER U JOIN  USED_GOODS_BOARD B ON U.USER_ID = B.WRITER_ID
GROUP BY B.WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY 1 DESC

